markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "Eadem mutata resurgo"
markdown: rdiscount

author: "lingfei"
atom-baseurl: "lingfeiwu.github.io"
disqus: "gopherwood"

navigations:
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Project
    class: fa fa-cubes
    href: /tags.html
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Link
    class: fa fa-link
    href: /links.html

