markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "如故"
markdown: rdiscount

author: "lingfei"
atom-baseurl: "lingfeiwu.github.io"
disqus: "gopherwood"

navigations:
  - title: About
    class: fa fa-user fa-lg
    href: /about.html
  - title: Project
    class: fa fa-th-large fa-lg
    href: /project/
  - title: Tag
    class: fa fa-tags fa-lg
    href: /tags.html
  - title: Archive
    class: fa fa-list-ul fa-lg
    href: /archive.html
  - title: Link
    class: fa fa-link fa-lg
    href: /links.html

